### ISSUE TITLE
NameError: name 'leia' is not defined

### ISSUE THREAD

**Issue by csantanaes** [rafaelgreca/Sentiment-Analysis-Twitter-PT#1]
Olá Rafael

O que significa df['leia'] = df['text'].apply(leia)
Importei um daframe = df com dados do twitter e recebi a imagem de erro abaixo. Pode ajudar?
no meu colab tenho o arquivo leia. py  ... 

![image](https://user-images.githubusercontent.com/7091412/132936296-937d97d3-dcaa-494b-87fc-63a743813c29.png)

**Comment by rafaelgreca** [comment]
Opa, beleza @csantanaes?

Dei um refatorada no código para ficar melhor de entender. Mas o leia em questão era uma função que estava em outro notebook (o models.ipnyb) e que tava dentro da pasta Models. Passei tudo para o arquivo principal (main.ipnyb) e melhorei algumas coisas. O código da limpeza dos dados ainda está em outro notebook. O que você pode fazer para utilizar no Colab é passar toda aquelas funções para o main.ipynb.

Mas respondendo a sua pergunta, o apply vai aplicar a função que for passada como parâmetro naquele dataset (ou em uma coluna específica, que é o meu caso). No seu print em questão ele pega a coluna de text, onde estão os tweets depois do pré-processamento, e aplica a função chamada leia, que aplica o método LeIA para classificar os tweets. O resultado dessa função será adicionado numa nova coluna, chamada de leia, no dataframe. Na imagem abaixo é possível verificar o que ocorre (essa coluna cleaned_text foi adiciona agora).

![Screenshot from 2021-09-11 11-21-08](https://user-images.githubusercontent.com/36083766/132951007-22034ecc-4676-42ba-8889-7c97add509a3.png)

Ah, também refatorei o código do TextBlob, antes ele tava muito demorado e não apresentava bons resultados, e adicionei o arquivo ''requirements.txt" caso tenha dificuldade em baixar algumas das bibliotecas utilizadas. Obrigado pela issue! Espero que tenha te ajudado. E, caso precisar de mais alguma ajuda, fique a vontade para criar outra issue ou entrar em contato comigo. Ajudarei sempre quando tiver tempo. Abraços!

**Comment by rafaelgreca** [comment]
Se tiver mais alguma sugestão de melhoria ou atualização no código, tipo alguns métodos novos para classificar os tweets, fique a vontade também para comentar. Ah, não esqueça de tirar as linhas: 
`
    data = data.sample(500)
    data = data.reset_index()
    data = data.drop(columns=['index'])
` 
que estão na célula do pré-processamento. Coloquei elas pq o dataset que utilizei é muito grande e ia demorar muito tempo para rodar as funções, então só peguei uma pequena parte do dataset. :)
